/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CalendarAgendaRouteImport } from './routes/calendar/agenda'
import { Route as CalendarDayRouteImport } from './routes/calendar/day'
import { Route as CalendarMonthRouteImport } from './routes/calendar/month'
import { Route as CalendarWeekRouteImport } from './routes/calendar/week'
import { Route as CalendarYearRouteImport } from './routes/calendar/year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarAgendaRoute = CalendarAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => CalendarRoute,
} as any)
const CalendarDayRoute = CalendarDayRouteImport.update({
  id: '/day',
  path: '/day',
  getParentRoute: () => CalendarRoute,
} as any)
const CalendarMonthRoute = CalendarMonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => CalendarRoute,
} as any)
const CalendarWeekRoute = CalendarWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => CalendarRoute,
} as any)
const CalendarYearRoute = CalendarYearRouteImport.update({
  id: '/year',
  path: '/year',
  getParentRoute: () => CalendarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/calendar/agenda': typeof CalendarAgendaRoute
  '/calendar/day': typeof CalendarDayRoute
  '/calendar/month': typeof CalendarMonthRoute
  '/calendar/week': typeof CalendarWeekRoute
  '/calendar/year': typeof CalendarYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/calendar/agenda': typeof CalendarAgendaRoute
  '/calendar/day': typeof CalendarDayRoute
  '/calendar/month': typeof CalendarMonthRoute
  '/calendar/week': typeof CalendarWeekRoute
  '/calendar/year': typeof CalendarYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/calendar/agenda': typeof CalendarAgendaRoute
  '/calendar/day': typeof CalendarDayRoute
  '/calendar/month': typeof CalendarMonthRoute
  '/calendar/week': typeof CalendarWeekRoute
  '/calendar/year': typeof CalendarYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/calendar/agenda'
    | '/calendar/day'
    | '/calendar/month'
    | '/calendar/week'
    | '/calendar/year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/calendar/agenda'
    | '/calendar/day'
    | '/calendar/month'
    | '/calendar/week'
    | '/calendar/year'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/calendar/agenda'
    | '/calendar/day'
    | '/calendar/month'
    | '/calendar/week'
    | '/calendar/year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/agenda': {
      id: '/calendar/agenda'
      path: '/agenda'
      fullPath: '/calendar/agenda'
      preLoaderRoute: typeof CalendarAgendaRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/calendar/day': {
      id: '/calendar/day'
      path: '/day'
      fullPath: '/calendar/day'
      preLoaderRoute: typeof CalendarDayRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/calendar/month': {
      id: '/calendar/month'
      path: '/month'
      fullPath: '/calendar/month'
      preLoaderRoute: typeof CalendarMonthRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/calendar/week': {
      id: '/calendar/week'
      path: '/week'
      fullPath: '/calendar/week'
      preLoaderRoute: typeof CalendarWeekRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/calendar/year': {
      id: '/calendar/year'
      path: '/year'
      fullPath: '/calendar/year'
      preLoaderRoute: typeof CalendarYearRouteImport
      parentRoute: typeof CalendarRoute
    }
  }
}

interface CalendarRouteChildren {
  CalendarAgendaRoute: typeof CalendarAgendaRoute
  CalendarDayRoute: typeof CalendarDayRoute
  CalendarMonthRoute: typeof CalendarMonthRoute
  CalendarWeekRoute: typeof CalendarWeekRoute
  CalendarYearRoute: typeof CalendarYearRoute
}

const CalendarRouteChildren: CalendarRouteChildren = {
  CalendarAgendaRoute: CalendarAgendaRoute,
  CalendarDayRoute: CalendarDayRoute,
  CalendarMonthRoute: CalendarMonthRoute,
  CalendarWeekRoute: CalendarWeekRoute,
  CalendarYearRoute: CalendarYearRoute,
}

const CalendarRouteWithChildren = CalendarRoute._addFileChildren(
  CalendarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
